name: Deployw to Production

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
         REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         REPOSITORY: my-app
         IMAGE_TAG: latest
      run: |
          docker build -t myapp .
          docker tag myapp:latest 654654608593.dkr.ecr.eu-north-1.amazonaws.com/myapp:latest
          docker push 654654608593.dkr.ecr.eu-north-1.amazonaws.com/myapp:latest
    

    - name: Deploy with Terraform
      run: |
        cd infrastructure
        terraform init
        terraform apply -auto-approve -var="image_tag=latest" -var="environment=production"
